apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-preview
  labels:
    app: web-balancer
    type: frontend
spec:
  selector:
    app: web-balancer
    version: 1.0
  ports:
    - name: httpd-svc-preview
      port: 80
      targetPort: 80
      nodePort: 30009
  type: LoadBalancer
