apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-balancer
  labels:
    app: web-balancer
    type: frontend
spec:
  selector:
    app: web-balancer
    version: "latest"
  ports:
    - name: httpd-svc-balancer
      port: 80
      targetPort: 80
      protocol: TCP
  #type: LoadBalancer
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout 
metadata:
  name: httpd-svc-balancer
  labels:
    app: web-balancer
    tier: frontend
spec:
  selector:
    matchLabels:
      app: web-balancer
  replicas: 5
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: web-balancer
        #version: "latest"
        tier: frontend
    spec:
      containers:
        - name: httpd-svc-balancer
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  strategy:
    blueGreen:
      activeService: httpd-svc-balancer
      previewService: httpd-svc-preview

